dist: trusty
sudo: true

language: csharp

mono:
    - latest
    - 4.2.4 # default on Fedora 24

install:
    - sudo apt-get install -y python3 python3-pip
    - sudo pip3 install behave
    - cat `which behave`

env:
    - BUILD_CONFIGURATION=Release
    - BUILD_CONFIGURATION=Debug

script:
    - nuget restore
    - xbuild /p:Configuration=$BUILD_CONFIGURATION SocialNetwork.sln
    - behave

