image: Visual Studio 2015

configuration: 
    - Debug
    - Release

build:
    verbosity: normal

install:
    - set PATH=C:\Python35-x64\;%PATH%
    - set PATH=C:\Python35-x64\scripts;%PATH%
    - pip install behave

test_script:
    - behave
