image: Visual Studio 2015

configuration: 
    - Debug
    - Release

build:
    verbosity: normal

install:
    - set PATH=C:\Python35-x64\;%PATH%
    - set PATH=C:\Python35-x64\scripts;%PATH%
    - pip3 install behave
    - nuget restore

test_script:
    - packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe SocialNetworkTests\bin\x86\%CONFIGURATION%\SocialNetworkTests.dll
    - behave
